version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 80:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 918918918
      POSTGRES_USER: postgres
      POSTGRES_DB: socialnetwork
    ports:
    - 5432:5432
  # pgadmin:
  #   image: 
      
