
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
          - containerPort: 5432
            name: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef: 
                name: postgres-secret
                key: postgres-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef: 
                name: postgres-config
                key: dbname
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-persistent-data
      volumes:
        - name: postgres-persistent-data
          persistentVolumeClaim:
             claimName: postgres-pvc
        
---
apiVersion: v1
kind: Service
metadata: 
  name: postgres-service
spec:
  selector: 
    app: postgres
  type: nodePort
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30020
    