apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=
  postgres-password: OTE4OTE4OTE4

---
apiVersion: v1
kind: ConfigMap 
metadata: 
  name: postgres-config
data:
  dbhost: postgres-service
  dbname: socialnetwork
   