default_context:
  project_name: 'demo-project'
  project_slug: 'demo-project'
  domain_main: 'demo-project.com'
  domain_staging: 'stag.demo-project.com'
  docker_swarm_stack_name_main: 'demo-project-com'
  docker_swarm_stack_name_staging: 'stag-demo-project-com'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  first_superuser: 'root'
  first_superuser_password: '918918918'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.demo-project.com", "https://stag.demo-project.com", "https://demo-project.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@demo-project.com'
  postgres_password: '918918918'
  pgadmin_default_user: 'root'
  pgadmin_default_user_password: '918918918'
  traefik_constraint_tag: 'demo-project.com'
  traefik_constraint_tag_staging: 'stag.demo-project.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:918918918'
  sentry_dsn: ''
  docker_image_prefix: 'texnder'
  docker_image_backend: 'texnder/full-stack-fastapi-postgres'
  docker_image_celeryworker: 'texnderceleryworker'
  docker_image_frontend: 'texnder/full-stack-frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
