apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels: 
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: fastapi
  template:
    metadata:
      labels: 
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: texnder/fastapi
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: LoadBalancer
  selector: 
    app: fastapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001